export const Categories = [
    "Tech",
    "Design",
    "Business",
    "Web 3",
    "Investing",
    // "Books",
    // "Mental Health",
    // "Economy",
    // "Food",
    // "GeoPolitics",
    // "Travel",
    // "Philosophy",
    // "Tech",
    // "Design",
    // "Business",
    // "Web 3",
    // "Investing",
]