export const Categories:string[] = [
    "Tech",
    "Science",
    "Business",
    "Web3",
    "Investing",
    "Books",
    "Mental Health",
    "Economy",
    "Food",
    "GeoPolitics",
    "Cultural",
    "Design",
    "Fashion",
    "Career",
    "Fitness",
    "Politics",
]